package com.grpc.grpc;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.widget.Toast;

import androidx.annotation.RequiresApi;

import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Image;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.io.image.ImageData;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.element.Text;


import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public class PDFReportGenerator {

    @RequiresApi(api = Build.VERSION_CODES.TIRAMISU)
    public static File generatePDFReport(String reportType, String reportName, String content, Context context, List<Uri> imageUris) {
        File pdfFolder = new File(context.getExternalFilesDir(null), "GRPEST REPORTS");
        if (!pdfFolder.exists()) {
            pdfFolder.mkdirs();
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
        String currentDate = sdf.format(new Date());
        String sanitizedReportName = reportName.replaceAll("[^a-zA-Z0-9]", "_") + "_" + currentDate + ".pdf";
        File pdfFile = new File(pdfFolder, sanitizedReportName);

        try (PdfWriter writer = new PdfWriter(new FileOutputStream(pdfFile))) {
            PdfDocument pdfDocument = new PdfDocument(writer);
            Document document = new Document(pdfDocument);

            try {
                int drawableResourceId = context.getResources().getIdentifier("logo", "drawable", context.getPackageName());
                ImageData logoData = ImageDataFactory.create(context.getResources().openRawResource(drawableResourceId).readAllBytes());
                Image logo = new Image(logoData).scaleToFit(200, 200).setHorizontalAlignment(com.itextpdf.layout.property.HorizontalAlignment.CENTER);
                document.add(logo);
            } catch (Exception e) {
                Toast.makeText(context, "Error loading logo from drawable", Toast.LENGTH_SHORT).show();
            }

            // Adding a watermark (faded image using setTransparency)
            try {
                int watermarkResourceId = context.getResources().getIdentifier("bk", "drawable", context.getPackageName());
                ImageData watermarkData = ImageDataFactory.create(context.getResources().openRawResource(watermarkResourceId).readAllBytes());
                Image watermark = new Image(watermarkData).scaleToFit(500, 500).setFixedPosition(150, 250);
                watermark.setOpacity(0.1f);
                document.add(watermark);
            } catch (Exception e) {
                Toast.makeText(context, "Error adding watermark", Toast.LENGTH_SHORT).show();
            }

            document.add(new Paragraph("Good Riddance Pest Control Report")
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(20)
                    .setBold()
                    .setFontColor(ColorConstants.BLUE));

            String[] reportDetails = content.split("\\n");
            for (String detail : reportDetails) {
                String[] splitDetail = detail.split(":", 2);
                if (splitDetail.length == 2) {
                    Text label = new Text(splitDetail[0].trim()).setFontColor(ColorConstants.BLACK).setUnderline().setBold().setFontSize(16);
                    document.add(new Paragraph(label));

                    Paragraph valuePara = new Paragraph(splitDetail[1].trim()).setFontColor(ColorConstants.BLACK).setFontSize(14);
                    document.add(valuePara);
                } else {
                    document.add(new Paragraph(detail.trim()).setFontColor(ColorConstants.BLACK));
                }
            }


            document.add(new Paragraph("This report was generated by GRPC Reporting System")
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontColor(ColorConstants.BLACK)
                    .setFontSize(12));

            document.close();

            Toast.makeText(context, "PDF Created Successfully!", Toast.LENGTH_SHORT).show();

            Intent intent = new Intent(context, MainActivity.class);
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
            context.startActivity(intent);

            return pdfFile;

        } catch (IOException e) {
            e.printStackTrace();
            Toast.makeText(context, "Error Creating PDF!", Toast.LENGTH_SHORT).show();
            return null;
        }
    }
}