package com.grpc.grpc;

import android.content.Context;

/**
 * Centralized flavor-aware branding strings for PDFs and filenames.
 *
 * IMPORTANT: This class must not change GRPC production output; it only replaces hardcoded text
 * with resource lookups that default to existing GRPC values.
 */
public final class TenantBranding {
    private TenantBranding() {}

    public static String companyName(Context c) {
        return c.getString(R.string.pdf_company_name);
    }

    public static String reportTitle(Context c) {
        return c.getString(R.string.pdf_report_title);
    }

    public static String actionFormTitle(Context c) {
        return c.getString(R.string.pdf_action_form_title);
    }

    public static String defaultFooterText(Context c) {
        return c.getString(R.string.pdf_footer_text);
    }

    public static String defaultWatermarkText(Context c) {
        return c.getString(R.string.pdf_default_watermark_text);
    }

    public static String filenamePrefix(Context c) {
        return c.getString(R.string.pdf_filename_prefix);
    }

    public static String companyWebsite(Context c) {
        return c.getString(R.string.pdf_company_website);
    }

    public static String companyWebsiteShort(Context c) {
        return c.getString(R.string.pdf_company_website_short);
    }

    /** Matches the historical GRPC footer format: "{Company} -- {Website}" */
    public static String footerCompanyWebsiteLine(Context c) {
        return companyName(c) + " -- " + companyWebsite(c);
    }

    /** Some PDFs historically used: "{Company} - {Website}" */
    public static String companyWebsiteLineDash(Context c) {
        return companyName(c) + " - " + companyWebsite(c);
    }

    public static String autoGeneratedNote(Context c) {
        return c.getString(R.string.pdf_auto_generated_note);
    }

    public static String companyAbbrev(Context c) {
        return c.getString(R.string.pdf_company_abbrev);
    }

    public static String eraTitle(Context c) {
        return c.getString(R.string.pdf_era_title);
    }
}

