package com.grpc.grpc.core;

import com.grpc.grpc.R;

import android.content.Context;

/**
 * Centralized flavor-aware branding for PDFs and filenames.
 * Production (grpc flavor) uses Good Riddance Pest Control strings; demo/offline override in their res/values.
 */
public final class TenantBranding {
    private TenantBranding() {}

    public static String companyName(Context c) {
        return c.getString(R.string.pdf_company_name);
    }

    public static String reportTitle(Context c) {
        return c.getString(R.string.pdf_report_title);
    }

    public static String actionFormTitle(Context c) {
        return c.getString(R.string.pdf_action_form_title);
    }

    public static String defaultFooterText(Context c) {
        return c.getString(R.string.pdf_footer_text);
    }

    public static String defaultWatermarkText(Context c) {
        return c.getString(R.string.pdf_default_watermark_text);
    }

    public static String filenamePrefix(Context c) {
        return c.getString(R.string.pdf_filename_prefix);
    }

    public static String companyWebsite(Context c) {
        return c.getString(R.string.pdf_company_website);
    }

    public static String companyWebsiteShort(Context c) {
        return c.getString(R.string.pdf_company_website_short);
    }

    /** Matches the historical GRPC footer format: "{Company} -- {Website}" */
    public static String footerCompanyWebsiteLine(Context c) {
        return companyName(c) + " -- " + companyWebsite(c);
    }

    /** Some PDFs historically used: "{Company} - {Website}" */
    public static String companyWebsiteLineDash(Context c) {
        return companyName(c) + " - " + companyWebsite(c);
    }

    public static String autoGeneratedNote(Context c) {
        return c.getString(R.string.pdf_auto_generated_note);
    }

    public static String companyAbbrev(Context c) {
        return c.getString(R.string.pdf_company_abbrev);
    }

    public static String eraTitle(Context c) {
        return c.getString(R.string.pdf_era_title);
    }

    /** Folder name for report PDFs (e.g. GRPEST REPORTS). Must be filesystem-safe. */
    public static String reportsFolderName(Context c) {
        return c != null ? c.getString(R.string.reports_folder_name) : "GRPEST REPORTS";
    }

    /** Folder name for quotation PDFs (e.g. GRPEST_QUOTES). Must be filesystem-safe. */
    public static String quotesFolderName(Context c) {
        return c != null ? c.getString(R.string.quotes_folder_name) : "GRPEST_QUOTES";
    }
}

